import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import DesktopNavigation from "@/components/layout/DesktopNavigation";
import MobileNavigation from "@/components/layout/MobileNavigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <div className="min-h-screen">
              <MobileNavigation />

              <div className="max-w-7xl mx-auto">
                <div className="grid grid-cols-1 md:grid-cols-12">
                  <div className="hidden md:block md:col-span-1 lg:col-span-3">
                    <DesktopNavigation />
                  </div>

                  <div className="md:col-span-11 lg:col-span-9 px-3 md:p-5 p-3">
                    <main>{children}</main>

                    <footer className="grid grid-cols-1 xl:grid-cols-10 mb-16 md:mb-0">
                      <div className="xl:col-span-6 text-xs text-muted-foreground/50 text-center">
                        <p className="mt-2">
                          &copy; {new Date().getFullYear()} Nexocial by Dimas Maulana. All Rights Reserved.
                        </p>
                      </div>
                    </footer>
                  </div>
                </div>
              </div>
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
